CatalogsOfFilms/Models/Film/AddFilmModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models.Film
{
    public class AddFilmModel
    {
        [Required]
        [StringLength(100)]
        [Display(Name = nameof(Resources.Film.Name), ResourceType = typeof(Resources.Film))]
        public string Name { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = nameof(Resources.Film.Description), ResourceType = typeof(Resources.Film))]
        public string Description { get; set; }

        [Required]
        [Range(1900, 2100)]
        [Display(Name = nameof(Resources.Film.Year), ResourceType = typeof(Resources.Film))]
        public int? Year { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = nameof(Resources.Film.Producer), ResourceType = typeof(Resources.Film))]
        public string Producer { get; set; }
    }
}

CatalogsOfFilms/Models/Film/DetailsModel.cs
namespace Web.Models.Film
{
    public class DetailsModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public int Year { get; set; }

        public string Producer { get; set; }

        public string Author { get; set; }

        public byte[] Poster { get; set; }
    }
}

CatalogsOfFilms/Models/Film/EditFilmModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models.Film
{
    public class EditFilmModel
    {
        public int Id { get; set; }

        [StringLength(100)]
        [Display(Name = nameof(Resources.Film.Name), ResourceType = typeof(Resources.Film))]
        public string Name { get; set; }

        [StringLength(1000)]
        [Display(Name = nameof(Resources.Film.Description), ResourceType = typeof(Resources.Film))]
        public string Description { get; set; }

        [Range(1900, 2100)]
        [Display(Name = nameof(Resources.Film.Year), ResourceType = typeof(Resources.Film))]
        public int? Year { get; set; }

        [StringLength(100)]
        [Display(Name = nameof(Resources.Film.Producer), ResourceType = typeof(Resources.Film))]
        public string Producer { get; set; }
    }
}

CatalogsOfFilms/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Common;
using Data;
using Data.Entities;
using Data.Repositories.Interfaces;
using Web.App;
using Web.Models.Film;

namespace Web.Controllers
{
    public class FilmController : Controller
    {
        public IUserRepository UserRepository { get; set; }
        public IFilmRepository FilmRepository { get; set; }
        public IUnitOfWork UnitOfWork { get; set; }

        public ActionResult AddFilm()
        {
            return View(new AddFilmModel());
        }

        [HttpPost]
        public ActionResult AddFilm(AddFilmModel m, HttpPostedFileBase poster)
        {
            if (ModelState.IsValid)
            {
                if (poster != null && poster.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(poster.InputStream))
                    {
                        var film = new Film
                        {
                            Name = m.Name,
                            Description = m.Description,
                            Producer = m.Producer,
                            Year = (int)m.Year,
                            Poster = reader.ReadBytes(poster.ContentLength),
                            UserId = CurrentUser.Get().Id,
                            CreatedAt = DateTime.UtcNow
                        };

                        var user = UserRepository.GetUserByEmail(CurrentUser.Get().Email);
                        if(user.Films == null)
                            user.Films = new List<Film> { film };
                        else
                            user.Films.Add(film);
                        FilmRepository.Add(film);
                        UnitOfWork.Commit();
                    }

                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("poster", Resources.Film.FileNotChanged);
            }
            return View(m);
        }

        public ActionResult EditFilm(string eId)
        {
            var film = FilmRepository.GetById(Cryptographer.Decode(eId));
            var model = new EditFilmModel
            {
                Id = film.Id,
                Name = film.Name,
                Description = film.Description,
                Producer = film.Producer,
                Year = film.Year,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult EditFilm(EditFilmModel m, HttpPostedFileBase poster)
        {
            if (ModelState.IsValid)
            {
                var film = FilmRepository.GetById(m.Id);
                film.Name = m.Name;
                film.Description = m.Description;
                film.Year = (int)m.Year;
                film.Producer = m.Producer;

                if (poster != null && poster.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(poster.InputStream))
                    {
                        film.Poster = reader.ReadBytes(poster.ContentLength);
                    }
                }

                UnitOfWork.Commit();
                return RedirectToAction("Index", "Home");
            }
            return View(m);
        }

        public ActionResult Details(string eId)
        {
            var film = FilmRepository.GetById(Cryptographer.Decode(eId));

            var model = new DetailsModel
            {
                Id = film.Id,
                Name = film.Name,
                Description = film.Description,
                Year = film.Year,
                Producer = film.Producer,
                Poster = film.Poster,
                Author = UserRepository.GetById(film.UserId).Email
            };

            return View(model);
        }
    }
}

CatalogsOfFilms/Controllers/HomeController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Data.Repositories.Interfaces;
using PagedList;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IFilmRepository FilmRepository { get; set; }
        private const int DefaultPageSize = 6;

        public async Task<ActionResult> Index(int? page)
        {
            var pageNumber = page ?? 1;
            var films = await FilmRepository.GetAllAsync();

            return View(films.ToPagedList(pageNumber, DefaultPageSize));
        }
    }
}

CatalogsOfFilms/Views/Home/Part/_Films.cshtml
@model PagedList.IPagedList<Data.Entities.Film>
@using PagedList.Mvc
@using Common
@using Web.Resources

@Styles.Render("~/Content/PagedList.css")

<div class="row">
    @foreach (var film in Model)
    {
        <div class="col-lg-4 fix-height-block">
             <a href="@Url.Action("Details", "Film", new {eId = Cryptographer.Encode(film.Id)})">

                 <div class="col-md-4">
                     <h4>@film.Year</h4>
                     @{
                         var base64 = Convert.ToBase64String(film.Poster);
                         var poster = $"data:image/gif;base64,{base64}";
                     }
                     <img src="@poster" style="max-width: 100px; max-height: 200px;"/>
                 </div>
                 <div class="col-md-8">
                     <h4>@film.Name</h4>
                     <p><b>@Film.Producer:</b> @film.Producer</p>
                     
                     @{ var description = film.Description.Length > 100 ? film.Description.Substring(0, 100) + "..." : film.Description; }

                     <p><b>@Film.Description:</b> @description</p>
                 </div>
             </a>
        </div>
    }
</div>

@{
    var pageListOptions = PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
        new AjaxOptions {
            HttpMethod = "GET",
            UpdateTargetId = "listFilms"
        });
    pageListOptions.DisplayLinkToFirstPage = PagedListDisplayMode.Always;
    pageListOptions.DisplayLinkToLastPage = PagedListDisplayMode.Always;
}

<div class="pager navbar-fixed-bottom fix-pager">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), pageListOptions)
</div>